### ISSUE TITLE
Invalid URLs in Response

### ISSUE THREAD

**Issue by da1910** [DSCmatter/CodeNexus-API#4]
The URLs returned by the API have the source prepended, they're also sometimes relative URLs and sometimes absolute.

It would be helpful if they were always valid absolute URLs, for example the test screenshots provided show that YC links have `yc` at the start of each URL, and the guardian links variously do and do not have `https://www.theguardian.com` at the start of each URL

**Comment by DSCmatter** [comment]
It is the only case with yc, since yc has done it to prevent web scraping, I believe. If you can do anything to improve it, you're welcome!
